# Generated by Django 4.1.2 on 2022-11-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['first_name'], 'permissions': [('view_own_client', 'Can view own client'), ('edit_own_client', 'Can update, delete own client')]},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'permissions': [('view_own_contract', 'Can view own contract'), ('edit_own_contract', 'Can update, delete own contract')]},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'permissions': [('view_own_event', 'Can view own event'), ('edit_own_event', 'Can update, delete own event')]},
        ),
    ]
