# Generated by Django 4.1.2 on 2022-11-22 14:40

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # Create the groups
    Group.objects.get_or_create(name='Sales')
    Group.objects.get_or_create(name='Support')

    # Get the permissions
    view_client = Permission.objects.get(codename='view_client')
    add_client = Permission.objects.get(codename='add_client')
    change_client = Permission.objects.get(codename='change_client')
    delete_client = Permission.objects.get(codename='delete_client')

    view_event = Permission.objects.get(codename='view_event')
    add_event = Permission.objects.get(codename='add_event')
    change_event = Permission.objects.get(codename='change_event')
    delete_event = Permission.objects.get(codename='delete_event')

    view_contract = Permission.objects.get(codename='view_contract')
    add_contract = Permission.objects.get(codename='add_contract')
    change_contract = Permission.objects.get(codename='change_contract')
    delete_contract = Permission.objects.get(codename='delete_contract')

    # Assign the permissions to the groups
    sales_group = Group.objects.get(name='Sales')
    support_group = Group.objects.get(name='Support')

    sales_group.permissions.add(view_client, add_client, change_client, delete_client,
                                view_event, add_event, change_event, delete_event,
                                view_contract, add_contract, change_contract, delete_contract)

    support_group.permissions.add(view_client, view_event, view_contract)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_client_options_alter_client_sales_contact_and_more'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
