# Generated by Django 4.1.2 on 2022-11-24 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_contractstatus_alter_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crm.contractstatus'),
            preserve_default=False,
        ),
    ]
